In [1]:
import numpy as np
from kmodes import kmodes
import pandas as pd

In [2]:
data = pd.read_csv('budd_new_22_6_18.csv', index_col= 0 )

In [3]:
data

gender  current_city  open_to_other_branch  work_ex  dist_from_uni  \
0         0             0                     0      3.5            3.0   
1         0             1                     0      3.5            3.0   
2         1             1                     0      1.8            3.0   
3         0             2                     0      3.5            5.0   
4         0             3                     0      2.0           10.0   
..      ...           ...                   ...      ...            ...   
517       0             0                     0      3.0           10.0   
518       0            27                     1      3.0            3.0   
519       0            23                     0      4.0           10.0   
520       0            11                     0      2.0            5.0   
521       1            51                     0      0.0            3.0   

     rent_budget  alcohol  smoking  food_pref  cul_skills  ...  \
0            550        1        1          0           0  ...   
1            550        0        0          0           1  ...   
2            550        0        1          0           0  ...   
3            500        0        0          0           0  ...   
4            700        0        1          1           0  ...   
..           ...      ...      ...        ...         ...  ...   
517          550        0        0          0           1  ...   
518          500        0        1          0           0  ...   
519          500        2        1          2           0  ...   
520          500        1        1          1           0  ...   
521          550        0        0          0           0  ...   

     MS Mechanical Engineering  MS Project Management  Others  hall_yes_no  \
0                            0                      0       0            0   
1                            0                      0       0            0   
2                            0                      0       0            0   
3                            0                      0       0            1   
4                            0                      0       0            0   
..                         ...                    ...     ...          ...   
517                          0                      0       0            1   
518                          0                      0       0            0   
519                          0                      0       0            0   
520                          0                      0       0            0   
521                          0                      0       0            0   

     max_ppr  bhk_1  bhk_2  bhk_3  bhk_4  studio  
0        3.0      1      1      0      0       0  
1        3.0      1      1      1      1       0  
2        2.0      1      1      1      0       0  
3        3.0      1      1      1      1       0  
4        3.0      1      1      1      0       1  
..       ...    ...    ...    ...    ...     ...  
517      4.0      1      1      1      1       1  
518      2.0      1      1      1      1       1  
519      2.0      0      1      1      0       0  
520      3.0      1      1      0      0       0  
521      1.0      1      1      0      0       1  

[522 rows x 32 columns]

###  Keeping male and female separate

In [4]:
f_data = data.loc[data['gender'] == 1]      #Females

In [5]:
m_data = data.loc[data['gender'] == 0]    #Males

In [6]:
m_data

gender  current_city  open_to_other_branch  work_ex  dist_from_uni  \
0         0             0                     0      3.5            3.0   
1         0             1                     0      3.5            3.0   
3         0             2                     0      3.5            5.0   
4         0             3                     0      2.0           10.0   
6         0             1                     0      3.0           10.0   
..      ...           ...                   ...      ...            ...   
516       0            34                     0      0.0            5.0   
517       0             0                     0      3.0           10.0   
518       0            27                     1      3.0            3.0   
519       0            23                     0      4.0           10.0   
520       0            11                     0      2.0            5.0   

     rent_budget  alcohol  smoking  food_pref  cul_skills  ...  \
0            550        1        1          0           0  ...   
1            550        0        0          0           1  ...   
3            500        0        0          0           0  ...   
4            700        0        1          1           0  ...   
6            400        0        0          0           2  ...   
..           ...      ...      ...        ...         ...  ...   
516          700        0        1          0           2  ...   
517          550        0        0          0           1  ...   
518          500        0        1          0           0  ...   
519          500        2        1          2           0  ...   
520          500        1        1          1           0  ...   

     MS Mechanical Engineering  MS Project Management  Others  hall_yes_no  \
0                            0                      0       0            0   
1                            0                      0       0            0   
3                            0                      0       0            1   
4                            0                      0       0            0   
6                            0                      0       0            0   
..                         ...                    ...     ...          ...   
516                          0                      0       0            0   
517                          0                      0       0            1   
518                          0                      0       0            0   
519                          0                      0       0            0   
520                          0                      0       0            0   

     max_ppr  bhk_1  bhk_2  bhk_3  bhk_4  studio  
0        3.0      1      1      0      0       0  
1        3.0      1      1      1      1       0  
3        3.0      1      1      1      1       0  
4        3.0      1      1      1      0       1  
6        2.0      1      1      0      0       1  
..       ...    ...    ...    ...    ...     ...  
516      4.0      1      1      1      0       0  
517      4.0      1      1      1      1       1  
518      2.0      1      1      1      1       1  
519      2.0      0      1      1      0       0  
520      3.0      1      1      0      0       0  

[401 rows x 32 columns]

In [7]:
def similarity_score(x, y):
    score = 0.0
    for i in range(len(x)):
        if x[i] == y[i]: score+=1
    return(score)

In [8]:
similarity_score(m_data.iloc[0], m_data.iloc[200])

26.0

In [9]:
m_data.shape

(401, 32)

In [10]:
simi_mat = np.zeros((m_data.shape[0], m_data.shape[0]))

In [11]:
for i in range(len(m_data)):
    for j in range(i, len(m_data)):
        simi_mat[i,j] = similarity_score(m_data.iloc[i], m_data.iloc[j])

In [12]:
simi_mat

array([[32., 26., 24., ..., 23., 21., 25.],
       [ 0., 32., 27., ..., 24., 19., 20.],
       [ 0.,  0., 32., ..., 24., 20., 22.],
       ...,
       [ 0.,  0.,  0., ..., 32., 21., 20.],
       [ 0.,  0.,  0., ...,  0., 32., 24.],
       [ 0.,  0.,  0., ...,  0.,  0., 32.]])

In [13]:
top_10_peruser = np.zeros((len(simi_mat), 10))
for i, row in enumerate(simi_mat):
    top_10_peruser[i, :] = np.argsort(-row)[1:11]

In [14]:
top_10_peruser

array([[382., 106., 394., ..., 196.,  27., 318.],
       [105., 335., 314., ...,  46.,  31., 103.],
       [ 11., 359.,  99., ...,  91., 131., 140.],
       ...,
       [399., 400., 396., ..., 267., 266., 265.],
       [400., 397., 271., ..., 266., 265., 264.],
       [272., 271., 270., ..., 265., 264., 263.]])

In [15]:
for j in top_10_peruser[0]:
    print(m_data.loc[j])

gender                                           0.0
current_city                                     4.0
open_to_other_branch                             0.0
work_ex                                          2.8
dist_from_uni                                    3.0
rent_budget                                    450.0
alcohol                                          0.0
smoking                                          0.0
food_pref                                        0.0
cul_skills                                       1.0
looking_for_roommate                             1.0
MS Biotechnology                                 0.0
MS Civil Engineering                             0.0
MS Computer Science                              1.0
MS Computer Systems Engineering                  0.0
MS Data Science                                  0.0
MS Electrical and Computer Engineering           0.0
MS Energy Systems                                0.0
MS Engineering Management                     

In [16]:
m_data.iloc[top_10_peruser[0]]

gender  current_city  open_to_other_branch  work_ex  dist_from_uni  \
500       0            51                     0      0.0            3.0   
134       0             0                     0      0.0            3.0   
514       0            51                     0      0.0            3.0   
158       0             0                     0      0.0            3.0   
332       0            55                     0      3.8            3.0   
101       0             3                     0      2.0            5.0   
31        0             1                     1      3.5            5.0   
248       0             9                     0      0.0            3.0   
32        0             6                     0      1.0            5.0   
413       0            68                     0      2.0            3.0   

     rent_budget  alcohol  smoking  food_pref  cul_skills  ...  \
500          550        1        1          0           0  ...   
134          450        1        1          1           0  ...   
514          550        1        1          1           0  ...   
158          500        1        1          1           0  ...   
332          550        1        1          0           0  ...   
101          500        1        1          1           0  ...   
31           500        0        1          0           0  ...   
248          500        1        1          0           0  ...   
32           700        0        1          0           0  ...   
413          450        0        1          0           0  ...   

     MS Mechanical Engineering  MS Project Management  Others  hall_yes_no  \
500                          0                      0       0            0   
134                          0                      0       0            0   
514                          0                      0       0            0   
158                          0                      0       0            0   
332                          0                      0       0            0   
101                          0                      0       0            0   
31                           0                      0       0            0   
248                          0                      0       0            0   
32                           0                      0       0            0   
413                          0                      0       0            0   

     max_ppr  bhk_1  bhk_2  bhk_3  bhk_4  studio  
500      2.0      1      1      0      0       0  
134      3.0      1      1      0      0       0  
514      2.0      1      1      0      0       0  
158      3.0      1      1      1      0       0  
332      2.0      1      1      1      0       0  
101      3.0      1      1      0      0       0  
31       3.0      1      1      0      0       0  
248      3.0      1      0      0      0       0  
32       3.0      1      1      0      0       0  
413      3.0      1      1      0      0       1  

[10 rows x 32 columns]

In [17]:
np.argsort(-np.array([0,1,2,3,4]))

array([4, 3, 2, 1, 0], dtype=int64)

In [18]:
from kmodes.kmodes import KModes

# random categorical data
data = np.random.choice(20, (100, 10))

km = KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 20, cost: 798.0
Run 1, iteration: 2/100, moves: 5, cost: 798.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 16, cost: 796.0
Run 2, iteration: 2/100, moves: 3, cost: 795.0
Run 2, iteration: 3/100, moves: 0, cost: 795.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 21, cost: 803.0
Run 3, iteration: 2/100, moves: 5, cost: 802.0
Run 3, iteration: 3/100, moves: 0, cost: 802.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 21, cost: 797.0
Run 4, iteration: 2/100, moves: 6, cost: 797.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 16, cost: 798.0
Run 5, iteration: 2/100, moves: 11, cost: 794.0
Run 5, iteration: 3/100, moves

In [19]:
km.cluster_centroids_

array([[ 5, 11,  7, 17,  8,  6, 13, 14, 16,  5],
       [14,  9,  0, 18, 13, 15, 19,  6, 10, 17],
       [15,  2,  5, 13,  6, 13,  1, 15,  3,  1],
       [12, 16, 17,  3,  6, 12, 11,  9,  5, 14]])

In [20]:
# random categorical data
km = KModes(n_clusters=6, init='Huang', n_init=5, verbose=1)
clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 16, cost: 771.0
Run 1, iteration: 2/100, moves: 4, cost: 771.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 15, cost: 768.0
Run 2, iteration: 2/100, moves: 1, cost: 768.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 23, cost: 764.0
Run 3, iteration: 2/100, moves: 6, cost: 761.0
Run 3, iteration: 3/100, moves: 2, cost: 761.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 31, cost: 754.0
Run 4, iteration: 2/100, moves: 12, cost: 752.0
Run 4, iteration: 3/100, moves: 1, cost: 752.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 14, cost: 771.0
Run 5, iteration: 2/100, moves: 4, cost: 767.0
Run 5, iteration: 3/100, moves

In [21]:
def matching_dissim(a, b=None):
    if b is None:
        b = a
    # rest of the method

km = KModes(n_clusters=6, init='Huang', n_init=5, verbose=1)
clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

# Calculate the dissimilarity matrix between categories
dissimilarity = km.cat_dissim(data)
print(dissimilarity)


Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 22, cost: 755.0
Run 1, iteration: 2/100, moves: 0, cost: 755.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 16, cost: 750.0
Run 2, iteration: 2/100, moves: 4, cost: 748.0
Run 2, iteration: 3/100, moves: 1, cost: 748.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 14, cost: 752.0
Run 3, iteration: 2/100, moves: 2, cost: 752.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 20, cost: 755.0
Run 4, iteration: 2/100, moves: 5, cost: 751.0
Run 4, iteration: 3/100, moves: 3, cost: 750.0
Run 4, iteration: 4/100, moves: 0, cost: 750.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 17, cost: 764.0
Run 5, iteration: 2/100, moves:

TypeError: matching_dissim() missing 1 required positional argument: 'b'

In [ ]:
km.cat_dissim()

# Custom KModes function